// =============================================================================
// Artha Sales Automation — Mock Data
// Realistic dataset matching exact Supabase production schema
// =============================================================================

import {
  Lead,
  Conversation,
  Message,
  Appointment,
  KnowledgeDoc,
  UnansweredQuestion,
  User,
  ActivityEvent,
  DashboardKPIs,
  TrendDataPoint,
  LeadDistribution,
  SystemStatus,
  RolePermissions,
} from './types';

// ---------------------------------------------------------------------------
// Helper: generate ISO dates relative to "now"
// ---------------------------------------------------------------------------
const now = new Date();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600000).toISOString();
const minutesAgo = (m: number) => new Date(now.getTime() - m * 60000).toISOString();

// ---------------------------------------------------------------------------
// LEADS (30 leads with varied scores, stages, and demographics)
// ---------------------------------------------------------------------------
export const mockLeads: Lead[] = [
  {
    id: 'L001',
    first_name: 'Rajesh',
    last_name: 'Kumar',
    company: 'Bank Mandiri',
    title: 'VP Data Strategy',
    industry: 'Banking',
    country: 'Indonesia',
    phone: '6281234567890',
    email: 'rajesh.kumar@bankmandiri.co.id',
    score: 'Hot',
    stage: 'QUALIFIED',
    opening_line: 'Hi Rajesh, noticed Bank Mandiri is scaling its data infrastructure...',
    pain_point: 'Legacy data silos preventing real-time analytics',
    date_added: daysAgo(14),
    message_sent: daysAgo(13),
    brief: 'Senior decision-maker at Indonesia\'s largest bank. Actively looking for MDM solutions.',
    last_contacted: daysAgo(1),
    last_reply_at: hoursAgo(6),
    signals: {
      intent_score: 22,
      fit_score: 24,
      momentum_score: 20,
      buying_readiness: 22,
      overall_score: 88,
      tier: 'Sales Ready',
      detected_signals: [
        { signal: 'Mentioned budget approval', points: 12, category: 'buying_readiness' },
        { signal: 'Asked about implementation timeline', points: 18, category: 'intent' },
        { signal: 'VP-level title at target company', points: 15, category: 'fit' },
        { signal: 'Requested case studies', points: 8, category: 'momentum' },
        { signal: 'Short reply detected', points: -5, category: 'momentum' },
      ],
    },
    next_action: 'Schedule demo call — lead is evaluating 2 vendors',
    handoff_required: true,
    handoff_reason: 'Lead requested to speak with a solutions architect',
    created_at: daysAgo(14),
    updated_at: hoursAgo(6),
  },
  {
    id: 'L002',
    first_name: 'Sarah',
    last_name: 'Tan',
    company: 'DBS Bank',
    title: 'Head of Analytics',
    industry: 'Banking',
    country: 'Singapore',
    phone: '6591234567',
    email: 'sarah.tan@dbs.com',
    score: 'Hot',
    stage: 'MEETING_BOOKED',
    opening_line: 'Hi Sarah, DBS has been doing impressive work in digital banking...',
    pain_point: 'Need for unified customer data platform',
    date_added: daysAgo(21),
    message_sent: daysAgo(20),
    brief: 'Head of Analytics at DBS. Very engaged, meeting booked for next week.',
    last_contacted: daysAgo(2),
    last_reply_at: daysAgo(2),
    signals: {
      intent_score: 24,
      fit_score: 23,
      momentum_score: 23,
      buying_readiness: 24,
      overall_score: 94,
      tier: 'Sales Ready',
      detected_signals: [
        { signal: 'Confirmed meeting attendance', points: 20, category: 'buying_readiness' },
        { signal: 'Shared internal requirements doc', points: 15, category: 'intent' },
        { signal: 'Asked about pricing tiers', points: 12, category: 'buying_readiness' },
        { signal: 'Multiple follow-up messages', points: 10, category: 'momentum' },
      ],
    },
    next_action: 'Prepare customized demo for Wednesday meeting',
    handoff_required: false,
    handoff_reason: '',
    created_at: daysAgo(21),
    updated_at: daysAgo(2),
  },
  {
    id: 'L003',
    first_name: 'Omar',
    last_name: 'Al Hammadi',
    company: 'Abu Dhabi Commercial Bank',
    title: 'Director of IT',
    industry: 'Banking',
    country: 'UAE',
    phone: '971501234567',
    email: 'omar.alhammadi@adcb.com',
    score: 'Hot',
    stage: 'MEETING_BOOKED',
    opening_line: 'Hi Omar, ADCB\'s digital transformation journey is remarkable...',
    pain_point: 'Data governance and compliance challenges',
    date_added: daysAgo(10),
    message_sent: daysAgo(9),
    brief: 'Director-level at ADCB. Interested in data governance solutions.',
    last_contacted: hoursAgo(18),
    last_reply_at: hoursAgo(18),
    signals: {
      intent_score: 21,
      fit_score: 22,
      momentum_score: 22,
      buying_readiness: 21,
      overall_score: 86,
      tier: 'Sales Ready',
      detected_signals: [
        { signal: 'Mentioned regulatory deadline', points: 18, category: 'buying_readiness' },
        { signal: 'Asked about compliance features', points: 14, category: 'intent' },
        { signal: 'Responded within 1 hour', points: 10, category: 'momentum' },
      ],
    },
    next_action: 'Send compliance-focused case study before meeting',
    handoff_required: false,
    handoff_reason: '',
    created_at: daysAgo(10),
    updated_at: hoursAgo(18),
  },
  {
    id: 'L004',
    first_name: 'Priya',
    last_name: 'Sharma',
    company: 'Infosys',
    title: 'Associate VP',
    industry: 'IT Services',
    country: 'India',
    phone: '919876543210',
    email: 'priya.sharma@infosys.com',
    score: 'Warm',
    stage: 'ENGAGED',
    opening_line: 'Hi Priya, Infosys has been a pioneer in digital services...',
    pain_point: 'Client data management across projects',
    date_added: daysAgo(7),
    message_sent: daysAgo(6),
    brief: 'AVP at Infosys, exploring data management for client delivery teams.',
    last_contacted: daysAgo(3),
    last_reply_at: daysAgo(3),
    signals: {
      intent_score: 18,
      fit_score: 20,
      momentum_score: 17,
      buying_readiness: 16,
      overall_score: 71,
      tier: 'Qualified',
      detected_signals: [
        { signal: 'Asked detailed technical questions', points: 14, category: 'intent' },
        { signal: 'IT Services company — good fit', points: 12, category: 'fit' },
        { signal: 'Reply gap > 48 hours', points: -8, category: 'momentum' },
        { signal: 'Mentioned evaluating options', points: 6, category: 'buying_readiness' },
      ],
    },
    next_action: 'Follow up with technical whitepaper',
    handoff_required: false,
    handoff_reason: '',
    created_at: daysAgo(7),
    updated_at: daysAgo(3),
  },
  {
    id: 'L005',
    first_name: 'Ahmad',
    last_name: 'Zulkifli',
    company: 'Petronas',
    title: 'Data Engineer',
    industry: 'Oil & Gas',
    country: 'Malaysia',
    phone: '60123456789',
    email: 'ahmad.z@petronas.com',
    score: 'Warm',
    stage: 'CURIOUS',
    opening_line: 'Hi Ahmad, Petronas is at the forefront of energy data innovation...',
    pain_point: 'Real-time pipeline monitoring data integration',
    date_added: daysAgo(5),
    message_sent: daysAgo(4),
    brief: 'Data Engineer exploring tools. Not a decision maker but could be an internal champion.',
    last_contacted: daysAgo(2),
    last_reply_at: daysAgo(3),
    signals: {
      intent_score: 14,
      fit_score: 16,
      momentum_score: 12,
      buying_readiness: 8,
      overall_score: 50,
      tier: 'Engaged',
      detected_signals: [
        { signal: 'Asked about API capabilities', points: 10, category: 'intent' },
        { signal: 'Engineer title — not decision maker', points: -5, category: 'fit' },
        { signal: 'Oil & Gas — high-value industry', points: 12, category: 'fit' },
      ],
    },
    next_action: 'Send API documentation and suggest connecting with his manager',
    handoff_required: false,
    handoff_reason: '',
    created_at: daysAgo(5),
    updated_at: daysAgo(2),
  },
  {
    id: 'L006',
    first_name: 'Ananya',
    last_name: 'Patel',
    company: 'Reliance Jio',
    title: 'Senior Manager — BI',
    industry: 'Telecommunications',
    country: 'India',
    phone: '919123456789',
    email: 'ananya.patel@jio.com',
    score: 'Hot',
    stage: 'QUALIFIED',
    opening_line: 'Hi Ananya, Jio\'s data volumes must be staggering...',
    pain_point: 'Scaling BI dashboards across regional teams',
    date_added: daysAgo(12),
    message_sent: daysAgo(11),
    brief: 'Senior Manager at Jio, needs to unify BI across 15+ regional offices.',
    last_contacted: daysAgo(1),
    last_reply_at: daysAgo(1),
    signals: {
      intent_score: 20,
      fit_score: 21,
      momentum_score: 19,
      buying_readiness: 18,
      overall_score: 78,
      tier: 'Qualified',
      detected_signals: [
        { signal: 'Mentioned team size (50+ analysts)', points: 10, category: 'fit' },
        { signal: 'Asked about enterprise licensing', points: 15, category: 'buying_readiness' },
        { signal: 'Requested ROI calculator', points: 12, category: 'intent' },
      ],
    },
    next_action: 'Send ROI calculator template',
    handoff_required: false,
    handoff_reason: '',
    created_at: daysAgo(12),
    updated_at: daysAgo(1),
  },
  {
    id: 'L007',
    first_name: 'Wei',
    last_name: 'Chen',
    company: 'Grab Financial',
    title: 'CTO',
    industry: 'FinTech',
    country: 'Singapore',
    phone: '6587654321',
    email: 'wei.chen@grab.com',
    score: 'Hot',
    stage: 'ENGAGED',
    opening_line: 'Hi Wei, Grab Financial\'s growth has been incredible...',
    pain_point: 'Real-time fraud detection data pipeline',
    date_added: daysAgo(8),
    message_sent: daysAgo(7),
    brief: 'CTO at Grab Financial. Exploring real-time data pipeline solutions.',
    last_contacted: hoursAgo(12),
    last_reply_at: hoursAgo(14),
    signals: {
      intent_score: 19,
      fit_score: 24,
      momentum_score: 18,
      buying_readiness: 14,
      overall_score: 75,
      tier: 'Qualified',
      detected_signals: [
        { signal: 'C-level executive', points: 20, category: 'fit' },
        { signal: 'Asked about latency benchmarks', points: 12, category: 'intent' },
        { signal: 'FinTech — high-value vertical', points: 10, category: 'fit' },
        { signal: 'Has not mentioned budget yet', points: -8, category: 'buying_readiness' },
      ],
    },
    next_action: 'Share latency benchmark report + propose technical deep-dive',
    handoff_required: false,
    handoff_reason: '',
    created_at: daysAgo(8),
    updated_at: hoursAgo(12),
  },
  {
    id: 'L008',
    first_name: 'Jessica',
    last_name: 'Morgan',
    company: 'Standard Chartered',
    title: 'Manager — Digital',
    industry: 'Banking',
    country: 'Hong Kong',
    phone: '85291234567',
    email: 'jessica.morgan@sc.com',
    score: 'Cold',
    stage: 'DNC',
    opening_line: 'Hi Jessica, StanChart\'s digital banking initiatives are impressive...',
    pain_point: '',
    date_added: daysAgo(30),
    message_sent: daysAgo(29),
    brief: 'Opted out — requested no further contact.',
    last_contacted: daysAgo(25),
    last_reply_at: daysAgo(25),
    signals: {
      intent_score: 2,
      fit_score: 15,
      momentum_score: 0,
      buying_readiness: 0,
      overall_score: 17,
      tier: 'Dormant',
      detected_signals: [
        { signal: 'Requested to stop messaging', points: -25, category: 'intent' },
        { signal: 'DNC flag set', points: -20, category: 'momentum' },
      ],
    },
    next_action: 'No action — DNC',
    handoff_required: false,
    handoff_reason: '',
    created_at: daysAgo(30),
    updated_at: daysAgo(25),
  },
  {
    id: 'L009',
    first_name: 'Vikram',
    last_name: 'Desai',
    company: 'Tata Consultancy Services',
    title: 'Practice Head — Data',
    industry: 'IT Services',
    country: 'India',
    phone: '919876123456',
    email: 'vikram.desai@tcs.com',
    score: 'Hot',
    stage: 'MEETING_BOOKED',
    opening_line: 'Hi Vikram, TCS\'s data practice is well-regarded across APAC...',
    pain_point: 'Need a vendor-agnostic data platform for client delivery',
    date_added: daysAgo(18),
    message_sent: daysAgo(17),
    brief: 'Practice Head at TCS, looking for vendor-agnostic data platform for client delivery.',
    last_contacted: daysAgo(1),
    last_reply_at: daysAgo(1),
    signals: {
      intent_score: 23,
      fit_score: 22,
      momentum_score: 24,
      buying_readiness: 23,
      overall_score: 92,
      tier: 'Sales Ready',
      detected_signals: [
        { signal: 'Meeting confirmed for Thursday', points: 20, category: 'buying_readiness' },
        { signal: 'Shared RFP document', points: 18, category: 'intent' },
        { signal: 'Responded same day', points: 12, category: 'momentum' },
        { signal: 'Practice Head — budget authority', points: 15, category: 'fit' },
      ],
    },
    next_action: 'Review RFP and prepare proposal',
    handoff_required: true,
    handoff_reason: 'RFP requires solutions architect involvement',
    created_at: daysAgo(18),
    updated_at: daysAgo(1),
  },
  {
    id: 'L010',
    first_name: 'Mei',
    last_name: 'Lin',
    company: 'Tokopedia',
    title: 'Product Manager',
    industry: 'E-Commerce',
    country: 'Indonesia',
    phone: '6289876543210',
    email: 'mei.lin@tokopedia.com',
    score: 'Warm',
    stage: 'CURIOUS',
    opening_line: 'Hi Mei, Tokopedia\'s marketplace data must be fascinating...',
    pain_point: 'Product recommendation engine data quality',
    date_added: daysAgo(4),
    message_sent: daysAgo(3),
    brief: 'PM at Tokopedia, early-stage interest in data quality tools.',
    last_contacted: daysAgo(2),
    last_reply_at: daysAgo(3),
    signals: {
      intent_score: 10,
      fit_score: 14,
      momentum_score: 10,
      buying_readiness: 6,
      overall_score: 40,
      tier: 'Exploring',
      detected_signals: [
        { signal: 'Asked general questions', points: 6, category: 'intent' },
        { signal: 'E-Commerce — good fit', points: 8, category: 'fit' },
        { signal: 'PM title — not direct buyer', points: -4, category: 'buying_readiness' },
      ],
    },
    next_action: 'Nurture with e-commerce case study',
    handoff_required: false,
    handoff_reason: '',
    created_at: daysAgo(4),
    updated_at: daysAgo(2),
  },
  {
    id: 'L011',
    first_name: 'Arun',
    last_name: 'Nair',
    company: 'Wipro',
    title: 'Delivery Manager',
    industry: 'IT Services',
    country: 'India',
    phone: '919845678901',
    email: 'arun.nair@wipro.com',
    score: 'Warm',
    stage: 'ENGAGED',
    opening_line: 'Hi Arun, Wipro\'s delivery excellence is well-known...',
    pain_point: 'Standardizing data pipelines across delivery centers',
    date_added: daysAgo(9),
    message_sent: daysAgo(8),
    brief: 'Delivery Manager at Wipro, interested in standardizing data pipelines.',
    last_contacted: daysAgo(2),
    last_reply_at: daysAgo(3),
    signals: {
      intent_score: 16,
      fit_score: 17,
      momentum_score: 14,
      buying_readiness: 12,
      overall_score: 59,
      tier: 'Engaged',
      detected_signals: [
        { signal: 'Asked about scalability', points: 10, category: 'intent' },
        { signal: 'IT Services — good vertical', points: 8, category: 'fit' },
        { signal: 'Delivery Manager — influences but doesn\'t decide', points: -3, category: 'buying_readiness' },
      ],
    },
    next_action: 'Send scalability benchmarks document',
    handoff_required: false,
    handoff_reason: '',
    created_at: daysAgo(9),
    updated_at: daysAgo(2),
  },
  {
    id: 'L012',
    first_name: 'Fatima',
    last_name: 'Al Zahra',
    company: 'Emirates NBD',
    title: 'Chief Data Officer',
    industry: 'Banking',
    country: 'UAE',
    phone: '971552345678',
    email: 'fatima.alzahra@emiratesnbd.com',
    score: 'Hot',
    stage: 'QUALIFIED',
    opening_line: 'Hi Fatima, Emirates NBD\'s data strategy has been groundbreaking...',
    pain_point: 'Enterprise-wide data governance framework',
    date_added: daysAgo(15),
    message_sent: daysAgo(14),
    brief: 'CDO at Emirates NBD, evaluating enterprise data governance platforms.',
    last_contacted: hoursAgo(8),
    last_reply_at: hoursAgo(10),
    signals: {
      intent_score: 22,
      fit_score: 25,
      momentum_score: 19,
      buying_readiness: 20,
      overall_score: 86,
      tier: 'Sales Ready',
      detected_signals: [
        { signal: 'CDO — top decision maker', points: 20, category: 'fit' },
        { signal: 'Mentioned Q3 implementation target', points: 16, category: 'buying_readiness' },
        { signal: 'Shared current vendor pain points', points: 14, category: 'intent' },
      ],
    },
    next_action: 'Schedule executive briefing',
    handoff_required: true,
    handoff_reason: 'CDO wants to meet CEO/founder',
    created_at: daysAgo(15),
    updated_at: hoursAgo(8),
  },
  {
    id: 'L013',
    first_name: 'Ravi',
    last_name: 'Krishnan',
    company: 'Mahindra Finance',
    title: 'IT Manager',
    industry: 'Financial Services',
    country: 'India',
    phone: '919812345678',
    email: 'ravi.k@mahindrafinance.com',
    score: 'Cold',
    stage: 'CONTACTED',
    opening_line: 'Hi Ravi, Mahindra Finance\'s digital journey is interesting...',
    pain_point: '',
    date_added: daysAgo(20),
    message_sent: daysAgo(19),
    brief: 'No response after initial contact. May not be the right person.',
    last_contacted: daysAgo(19),
    last_reply_at: '',
    signals: {
      intent_score: 0,
      fit_score: 12,
      momentum_score: 0,
      buying_readiness: 0,
      overall_score: 12,
      tier: 'Dormant',
      detected_signals: [
        { signal: 'No response to outreach', points: -15, category: 'momentum' },
        { signal: 'IT Manager — mid-level', points: 0, category: 'fit' },
      ],
    },
    next_action: 'One more follow-up in 7 days, then archive',
    handoff_required: false,
    handoff_reason: '',
    created_at: daysAgo(20),
    updated_at: daysAgo(19),
  },
  {
    id: 'L014',
    first_name: 'Siti',
    last_name: 'Rahman',
    company: 'Maybank',
    title: 'SVP Technology',
    industry: 'Banking',
    country: 'Malaysia',
    phone: '60129876543',
    email: 'siti.rahman@maybank.com',
    score: 'Warm',
    stage: 'ENGAGED',
    opening_line: 'Hi Siti, Maybank\'s tech modernization is impressive...',
    pain_point: 'Cross-border data reconciliation',
    date_added: daysAgo(11),
    message_sent: daysAgo(10),
    brief: 'SVP Tech at Maybank, exploring cross-border data solutions.',
    last_contacted: daysAgo(2),
    last_reply_at: daysAgo(2),
    signals: {
      intent_score: 17,
      fit_score: 21,
      momentum_score: 16,
      buying_readiness: 14,
      overall_score: 68,
      tier: 'Engaged',
      detected_signals: [
        { signal: 'SVP title — senior leadership', points: 14, category: 'fit' },
        { signal: 'Asked about multi-country deployment', points: 12, category: 'intent' },
        { signal: 'Banking — target vertical', points: 10, category: 'fit' },
        { signal: 'Mentioned "exploring options"', points: -4, category: 'buying_readiness' },
      ],
    },
    next_action: 'Send multi-country deployment guide',
    handoff_required: false,
    handoff_reason: '',
    created_at: daysAgo(11),
    updated_at: daysAgo(2),
  },
  {
    id: 'L015',
    first_name: 'Deepak',
    last_name: 'Mehta',
    company: 'HDFC Bank',
    title: 'GM — Digital Banking',
    industry: 'Banking',
    country: 'India',
    phone: '919988776655',
    email: 'deepak.mehta@hdfcbank.com',
    score: 'Warm',
    stage: 'CURIOUS',
    opening_line: 'Hi Deepak, HDFC\'s digital banking platform is best-in-class...',
    pain_point: 'Customer 360 view across channels',
    date_added: daysAgo(3),
    message_sent: daysAgo(2),
    brief: 'GM at HDFC Bank, just started conversation.',
    last_contacted: daysAgo(1),
    last_reply_at: daysAgo(1),
    signals: {
      intent_score: 12,
      fit_score: 22,
      momentum_score: 15,
      buying_readiness: 10,
      overall_score: 59,
      tier: 'Engaged',
      detected_signals: [
        { signal: 'GM — senior with budget access', points: 16, category: 'fit' },
        { signal: 'Banking — top target vertical', points: 12, category: 'fit' },
        { signal: 'Early conversation — exploring', points: 5, category: 'intent' },
      ],
    },
    next_action: 'Continue nurturing — share banking case study',
    handoff_required: false,
    handoff_reason: '',
    created_at: daysAgo(3),
    updated_at: daysAgo(1),
  },
  {
    id: 'L016',
    first_name: 'Nguyen',
    last_name: 'Thanh',
    company: 'VinGroup',
    title: 'Head of AI',
    industry: 'Conglomerate',
    country: 'Vietnam',
    phone: '84987654321',
    email: 'nguyen.thanh@vingroup.net',
    score: 'Warm',
    stage: 'CONTACTED',
    opening_line: 'Hi Nguyen, VinGroup\'s AI ambitions are remarkable...',
    pain_point: 'AI model training data management',
    date_added: daysAgo(2),
    message_sent: daysAgo(1),
    brief: 'Head of AI at VinGroup. New lead, recently contacted.',
    last_contacted: daysAgo(1),
    last_reply_at: '',
    signals: {
      intent_score: 5,
      fit_score: 18,
      momentum_score: 5,
      buying_readiness: 4,
      overall_score: 32,
      tier: 'Exploring',
      detected_signals: [
        { signal: 'Head of AI — good title', points: 12, category: 'fit' },
        { signal: 'No reply yet', points: -8, category: 'momentum' },
      ],
    },
    next_action: 'Wait for initial response',
    handoff_required: false,
    handoff_reason: '',
    created_at: daysAgo(2),
    updated_at: daysAgo(1),
  },
  {
    id: 'L017',
    first_name: 'Suresh',
    last_name: 'Babu',
    company: 'Tech Mahindra',
    title: 'Solution Architect',
    industry: 'IT Services',
    country: 'India',
    phone: '919765432109',
    email: 'suresh.babu@techmahindra.com',
    score: 'Cold',
    stage: 'COLD_LOGGED',
    opening_line: 'Hi Suresh, Tech Mahindra\'s solutions portfolio is impressive...',
    pain_point: '',
    date_added: daysAgo(25),
    message_sent: '',
    brief: 'Scored as Cold by AI — not a good fit at this time.',
    last_contacted: '',
    last_reply_at: '',
    signals: {
      intent_score: 3,
      fit_score: 8,
      momentum_score: 0,
      buying_readiness: 0,
      overall_score: 11,
      tier: 'Dormant',
      detected_signals: [
        { signal: 'Solution Architect — no budget authority', points: -6, category: 'fit' },
        { signal: 'AI scored as Cold', points: -15, category: 'intent' },
      ],
    },
    next_action: 'Archived — no action',
    handoff_required: false,
    handoff_reason: '',
    created_at: daysAgo(25),
    updated_at: daysAgo(25),
  },
  {
    id: 'L018',
    first_name: 'Li',
    last_name: 'Wei',
    company: 'Sea Group',
    title: 'VP Engineering',
    industry: 'Technology',
    country: 'Singapore',
    phone: '6598765432',
    email: 'li.wei@sea.com',
    score: 'Hot',
    stage: 'ENGAGED',
    opening_line: 'Hi Li, Sea Group\'s engineering culture is remarkable...',
    pain_point: 'Real-time data streaming infrastructure',
    date_added: daysAgo(6),
    message_sent: daysAgo(5),
    brief: 'VP Eng at Sea Group, interested in real-time streaming solutions.',
    last_contacted: hoursAgo(4),
    last_reply_at: hoursAgo(6),
    signals: {
      intent_score: 19,
      fit_score: 22,
      momentum_score: 18,
      buying_readiness: 16,
      overall_score: 75,
      tier: 'Qualified',
      detected_signals: [
        { signal: 'VP Engineering — technical decision maker', points: 16, category: 'fit' },
        { signal: 'Asked about Kafka integration', points: 12, category: 'intent' },
        { signal: 'Fast response times', points: 8, category: 'momentum' },
      ],
    },
    next_action: 'Share streaming architecture deep-dive',
    handoff_required: false,
    handoff_reason: '',
    created_at: daysAgo(6),
    updated_at: hoursAgo(4),
  },
  {
    id: 'L019',
    first_name: 'Kavitha',
    last_name: 'Sundaram',
    company: 'Zoho',
    title: 'Product Director',
    industry: 'SaaS',
    country: 'India',
    phone: '919654321098',
    email: 'kavitha.s@zoho.com',
    score: 'Warm',
    stage: 'CURIOUS',
    opening_line: 'Hi Kavitha, Zoho\'s product suite is impressively comprehensive...',
    pain_point: 'Cross-product data unification',
    date_added: daysAgo(4),
    message_sent: daysAgo(3),
    brief: 'Product Director at Zoho, exploring data unification across products.',
    last_contacted: daysAgo(2),
    last_reply_at: daysAgo(2),
    signals: {
      intent_score: 13,
      fit_score: 16,
      momentum_score: 14,
      buying_readiness: 8,
      overall_score: 51,
      tier: 'Engaged',
      detected_signals: [
        { signal: 'Product Director — strategic role', points: 10, category: 'fit' },
        { signal: 'SaaS company — build vs buy question', points: -4, category: 'buying_readiness' },
        { signal: 'Asked about integration APIs', points: 8, category: 'intent' },
      ],
    },
    next_action: 'Share integration documentation',
    handoff_required: false,
    handoff_reason: '',
    created_at: daysAgo(4),
    updated_at: daysAgo(2),
  },
  {
    id: 'L020',
    first_name: 'Mohammed',
    last_name: 'Al Rashid',
    company: 'Saudi Aramco',
    title: 'Digital Transformation Lead',
    industry: 'Oil & Gas',
    country: 'Saudi Arabia',
    phone: '966551234567',
    email: 'mohammed.r@aramco.com',
    score: 'Hot',
    stage: 'QUALIFIED',
    opening_line: 'Hi Mohammed, Aramco\'s digital transformation is world-leading...',
    pain_point: 'Enterprise data lake governance',
    date_added: daysAgo(13),
    message_sent: daysAgo(12),
    brief: 'DT Lead at Aramco, very interested in data lake governance solutions.',
    last_contacted: daysAgo(1),
    last_reply_at: daysAgo(1),
    signals: {
      intent_score: 21,
      fit_score: 24,
      momentum_score: 20,
      buying_readiness: 19,
      overall_score: 84,
      tier: 'Qualified',
      detected_signals: [
        { signal: 'Asked about on-premise deployment', points: 14, category: 'intent' },
        { signal: 'Aramco — enterprise budget', points: 18, category: 'fit' },
        { signal: 'Mentioned procurement process starting', points: 16, category: 'buying_readiness' },
      ],
    },
    next_action: 'Prepare on-premise deployment proposal',
    handoff_required: true,
    handoff_reason: 'Requires security compliance documentation',
    created_at: daysAgo(13),
    updated_at: daysAgo(1),
  },
  // Additional leads for volume...
  {
    id: 'L021', first_name: 'Tan', last_name: 'Boon Keat', company: 'OCBC Bank', title: 'VP Data', industry: 'Banking', country: 'Singapore', phone: '6591122334', email: 'tan.bk@ocbc.com', score: 'Warm', stage: 'ENGAGED', opening_line: 'Hi Tan, OCBC\'s data initiatives are impressive...', pain_point: 'Data quality monitoring', date_added: daysAgo(8), message_sent: daysAgo(7), brief: 'VP Data at OCBC.', last_contacted: daysAgo(2), last_reply_at: daysAgo(3), signals: { intent_score: 16, fit_score: 20, momentum_score: 14, buying_readiness: 13, overall_score: 63, tier: 'Engaged', detected_signals: [{ signal: 'Banking VP — good fit', points: 14, category: 'fit' }] }, next_action: 'Follow up with data quality whitepaper', handoff_required: false, handoff_reason: '', created_at: daysAgo(8), updated_at: daysAgo(2),
  },
  {
    id: 'L022', first_name: 'Amit', last_name: 'Verma', company: 'HCL Technologies', title: 'Practice Lead', industry: 'IT Services', country: 'India', phone: '919543210987', email: 'amit.verma@hcl.com', score: 'Warm', stage: 'CURIOUS', opening_line: 'Hi Amit, HCL\'s data practice is growing fast...', pain_point: 'Client onboarding data pipelines', date_added: daysAgo(3), message_sent: daysAgo(2), brief: 'Practice Lead at HCL, early interest.', last_contacted: daysAgo(1), last_reply_at: daysAgo(2), signals: { intent_score: 11, fit_score: 15, momentum_score: 10, buying_readiness: 7, overall_score: 43, tier: 'Exploring', detected_signals: [{ signal: 'Practice Lead — mid-level influence', points: 8, category: 'fit' }] }, next_action: 'Send onboarding automation case study', handoff_required: false, handoff_reason: '', created_at: daysAgo(3), updated_at: daysAgo(1),
  },
  {
    id: 'L023', first_name: 'Putri', last_name: 'Wijaya', company: 'Gojek', title: 'Data Science Manager', industry: 'Technology', country: 'Indonesia', phone: '6281987654321', email: 'putri.w@gojek.com', score: 'Warm', stage: 'CONTACTED', opening_line: 'Hi Putri, Gojek\'s data science team is doing fascinating work...', pain_point: 'Feature store management', date_added: daysAgo(1), message_sent: hoursAgo(20), brief: 'DS Manager at Gojek, newly contacted.', last_contacted: hoursAgo(20), last_reply_at: '', signals: { intent_score: 6, fit_score: 16, momentum_score: 4, buying_readiness: 3, overall_score: 29, tier: 'Exploring', detected_signals: [{ signal: 'Tech company — good fit', points: 10, category: 'fit' }] }, next_action: 'Wait for initial response', handoff_required: false, handoff_reason: '', created_at: daysAgo(1), updated_at: hoursAgo(20),
  },
  {
    id: 'L024', first_name: 'Rashid', last_name: 'Khan', company: 'National Bank of Bahrain', title: 'CIO', industry: 'Banking', country: 'Bahrain', phone: '97339876543', email: 'rashid.khan@nbb.com.bh', score: 'Hot', stage: 'QUALIFIED', opening_line: 'Hi Rashid, NBB\'s technology modernization is commendable...', pain_point: 'Core banking data migration', date_added: daysAgo(16), message_sent: daysAgo(15), brief: 'CIO at NBB, evaluating data migration platforms.', last_contacted: daysAgo(1), last_reply_at: daysAgo(1), signals: { intent_score: 20, fit_score: 23, momentum_score: 18, buying_readiness: 20, overall_score: 81, tier: 'Qualified', detected_signals: [{ signal: 'CIO — ultimate decision maker', points: 20, category: 'fit' }, { signal: 'Asked about migration timeline', points: 14, category: 'intent' }] }, next_action: 'Send migration assessment framework', handoff_required: false, handoff_reason: '', created_at: daysAgo(16), updated_at: daysAgo(1),
  },
  {
    id: 'L025', first_name: 'Nisha', last_name: 'Agarwal', company: 'Flipkart', title: 'Engineering Manager', industry: 'E-Commerce', country: 'India', phone: '919432109876', email: 'nisha.a@flipkart.com', score: 'Cold', stage: 'CONTACTED', opening_line: 'Hi Nisha, Flipkart\'s scale is incredible...', pain_point: '', date_added: daysAgo(22), message_sent: daysAgo(21), brief: 'No response after initial outreach.', last_contacted: daysAgo(21), last_reply_at: '', signals: { intent_score: 0, fit_score: 14, momentum_score: 0, buying_readiness: 0, overall_score: 14, tier: 'Dormant', detected_signals: [{ signal: 'No response', points: -15, category: 'momentum' }] }, next_action: 'Archive after 30 days', handoff_required: false, handoff_reason: '', created_at: daysAgo(22), updated_at: daysAgo(21),
  },
  {
    id: 'L026', first_name: 'Chen', last_name: 'Yu Ming', company: 'UOB', title: 'Head of Data Engineering', industry: 'Banking', country: 'Singapore', phone: '6596543210', email: 'chen.ym@uob.com.sg', score: 'Warm', stage: 'ENGAGED', opening_line: 'Hi Chen, UOB\'s data engineering team has been scaling...', pain_point: 'Data pipeline observability', date_added: daysAgo(7), message_sent: daysAgo(6), brief: 'Head of Data Eng at UOB, interested in observability tools.', last_contacted: daysAgo(1), last_reply_at: daysAgo(2), signals: { intent_score: 15, fit_score: 20, momentum_score: 15, buying_readiness: 12, overall_score: 62, tier: 'Engaged', detected_signals: [{ signal: 'Asked about monitoring dashboards', points: 10, category: 'intent' }, { signal: 'Banking — target vertical', points: 12, category: 'fit' }] }, next_action: 'Share observability demo video', handoff_required: false, handoff_reason: '', created_at: daysAgo(7), updated_at: daysAgo(1),
  },
  {
    id: 'L027', first_name: 'Arjun', last_name: 'Reddy', company: 'Razorpay', title: 'VP Platform', industry: 'FinTech', country: 'India', phone: '919321098765', email: 'arjun.r@razorpay.com', score: 'Hot', stage: 'ENGAGED', opening_line: 'Hi Arjun, Razorpay\'s platform scale is impressive...', pain_point: 'Payment data analytics at scale', date_added: daysAgo(5), message_sent: daysAgo(4), brief: 'VP Platform at Razorpay, discussing analytics needs.', last_contacted: hoursAgo(3), last_reply_at: hoursAgo(5), signals: { intent_score: 18, fit_score: 21, momentum_score: 20, buying_readiness: 15, overall_score: 74, tier: 'Qualified', detected_signals: [{ signal: 'VP Platform — budget holder', points: 16, category: 'fit' }, { signal: 'Active conversation — 8 turns', points: 12, category: 'momentum' }, { signal: 'FinTech — high value', points: 10, category: 'fit' }] }, next_action: 'Propose technical deep-dive session', handoff_required: false, handoff_reason: '', created_at: daysAgo(5), updated_at: hoursAgo(3),
  },
  {
    id: 'L028', first_name: 'Thuy', last_name: 'Nguyen', company: 'VPBank', title: 'Head of Digital', industry: 'Banking', country: 'Vietnam', phone: '84912345678', email: 'thuy.n@vpbank.com.vn', score: 'Warm', stage: 'CURIOUS', opening_line: 'Hi Thuy, VPBank\'s digital transformation is exciting...', pain_point: 'Customer data platform', date_added: daysAgo(2), message_sent: daysAgo(1), brief: 'Head of Digital at VPBank, early-stage interest.', last_contacted: daysAgo(1), last_reply_at: daysAgo(1), signals: { intent_score: 10, fit_score: 18, momentum_score: 12, buying_readiness: 6, overall_score: 46, tier: 'Exploring', detected_signals: [{ signal: 'Head of Digital — strategic role', points: 12, category: 'fit' }, { signal: 'Banking — target vertical', points: 10, category: 'fit' }, { signal: 'Just started conversation', points: 4, category: 'momentum' }] }, next_action: 'Continue nurturing with banking case studies', handoff_required: false, handoff_reason: '', created_at: daysAgo(2), updated_at: daysAgo(1),
  },
  {
    id: 'L029', first_name: 'Pawan', last_name: 'Gupta', company: 'Paytm', title: 'Director Engineering', industry: 'FinTech', country: 'India', phone: '919210987654', email: 'pawan.g@paytm.com', score: 'Cold', stage: 'COLD_LOGGED', opening_line: 'Hi Pawan, Paytm\'s scale challenges are unique...', pain_point: '', date_added: daysAgo(28), message_sent: '', brief: 'Scored as Cold — company in cost-cutting mode.', last_contacted: '', last_reply_at: '', signals: { intent_score: 2, fit_score: 10, momentum_score: 0, buying_readiness: 0, overall_score: 12, tier: 'Dormant', detected_signals: [{ signal: 'Company in cost-cutting mode', points: -12, category: 'buying_readiness' }, { signal: 'AI scored as Cold', points: -10, category: 'intent' }] }, next_action: 'Archived', handoff_required: false, handoff_reason: '', created_at: daysAgo(28), updated_at: daysAgo(28),
  },
  {
    id: 'L030', first_name: 'Dian', last_name: 'Sari', company: 'Bank Central Asia', title: 'SVP Data Analytics', industry: 'Banking', country: 'Indonesia', phone: '6281876543210', email: 'dian.sari@bca.co.id', score: 'Warm', stage: 'ENGAGED', opening_line: 'Hi Dian, BCA\'s analytics capabilities are market-leading...', pain_point: 'Cross-channel customer analytics', date_added: daysAgo(9), message_sent: daysAgo(8), brief: 'SVP at BCA, interested in cross-channel analytics.', last_contacted: daysAgo(1), last_reply_at: daysAgo(2), signals: { intent_score: 16, fit_score: 22, momentum_score: 15, buying_readiness: 13, overall_score: 66, tier: 'Engaged', detected_signals: [{ signal: 'SVP — senior leadership', points: 15, category: 'fit' }, { signal: 'Asked about visualization capabilities', points: 10, category: 'intent' }, { signal: 'Banking — top target', points: 12, category: 'fit' }] }, next_action: 'Share visualization demo', handoff_required: false, handoff_reason: '', created_at: daysAgo(9), updated_at: daysAgo(1),
  },
];

// ---------------------------------------------------------------------------
// CONVERSATIONS
// ---------------------------------------------------------------------------
export const mockConversations: Conversation[] = [
  {
    id: 'C001',
    phone: '6281234567890',
    lead_id: 'L001',
    history: 'Maya: Hi Rajesh, noticed Bank Mandiri is scaling its data infrastructure. How are you managing data quality across your growing platform?\nRajesh: Yes, it\'s a challenge. We have multiple data silos and no unified governance.\nMaya: That\'s common at your scale. Our MDM solution has helped similar banks unify 50+ data sources. Would you like to see how?\nRajesh: Sure, can you share some case studies first?\nMaya: Absolutely! Here\'s our banking case study collection. Which area is most critical — customer data, transaction data, or compliance?\nRajesh: Compliance is our biggest pain point right now. We have a regulatory audit coming up in Q3.\nMaya: Perfect timing. Our governance module has helped 3 banks pass similar audits. I can arrange a compliance-focused demo. Would Tuesday or Thursday work?\nRajesh: Thursday afternoon works. But I\'d like to involve our Solutions Architect team too.',
    stage: 'QUALIFIED',
    turn_count: 8,
    summary: 'Rajesh is interested in MDM for compliance. Regulatory audit in Q3 driving urgency. Wants solutions architect involvement.',
    last_updated: hoursAgo(6),
    last_user_message: 'Thursday afternoon works. But I\'d like to involve our Solutions Architect team too.',
    last_bot_message: 'Perfect timing. Our governance module has helped 3 banks pass similar audits. I can arrange a compliance-focused demo. Would Tuesday or Thursday work?',
    last_action: 'REPLY',
    alert_sent: true,
    meeting_link_sent: false,
    brochure_sent: true,
    last_alert_reason: 'Lead reached QUALIFIED stage',
    last_signal: 'Mentioned regulatory deadline',
    locked_until: '',
    created_at: daysAgo(13),
  },
  {
    id: 'C002',
    phone: '6591234567',
    lead_id: 'L002',
    history: 'Maya: Hi Sarah, DBS has been doing impressive work in digital banking. How is your analytics team handling the data volume growth?\nSarah: We\'re actually looking for a unified CDP. Current setup is fragmented.\nMaya: That sounds like a perfect use case for our platform. We\'ve helped 5 banks build unified CDPs. Shall I share our approach?\nSarah: Yes please. Also, what are your pricing tiers?\nMaya: I\'ll send our enterprise pricing overview. For DBS\'s scale, I\'d recommend our Enterprise tier. Can we schedule a detailed walkthrough?\nSarah: Yes, how about Wednesday at 2 PM SGT?\nMaya: Perfect! I\'ve sent you a calendar invite. Looking forward to it!\nSarah: Got it, thanks. I\'ll also bring our Head of Engineering.',
    stage: 'MEETING_BOOKED',
    turn_count: 8,
    summary: 'Sarah needs a CDP. Meeting booked for Wednesday 2 PM. Will bring Head of Engineering.',
    last_updated: daysAgo(2),
    last_user_message: 'Got it, thanks. I\'ll also bring our Head of Engineering.',
    last_bot_message: 'Perfect! I\'ve sent you a calendar invite. Looking forward to it!',
    last_action: 'SEND_MEETING',
    alert_sent: true,
    meeting_link_sent: true,
    brochure_sent: true,
    last_alert_reason: 'Meeting booked',
    last_signal: 'Confirmed meeting',
    locked_until: daysAgo(-3),
    created_at: daysAgo(20),
  },
  {
    id: 'C003',
    phone: '971501234567',
    lead_id: 'L003',
    history: 'Maya: Hi Omar, ADCB\'s digital transformation journey is remarkable. How are you handling data governance across your expanding digital services?\nOmar: Governance is our top priority. We need to comply with new CBUAE regulations.\nMaya: We have deep experience with Middle East banking regulations. Our platform supports CBUAE, SAMA, and DFSA compliance frameworks out of the box.\nOmar: That\'s interesting. Can we set up a call to discuss?\nMaya: Absolutely! I\'ve prepared a compliance-focused overview. Here\'s a meeting link for this week.',
    stage: 'MEETING_BOOKED',
    turn_count: 5,
    summary: 'Omar needs CBUAE compliance support. Meeting booked.',
    last_updated: hoursAgo(18),
    last_user_message: 'That\'s interesting. Can we set up a call to discuss?',
    last_bot_message: 'Absolutely! I\'ve prepared a compliance-focused overview. Here\'s a meeting link for this week.',
    last_action: 'SEND_MEETING',
    alert_sent: true,
    meeting_link_sent: true,
    brochure_sent: false,
    last_alert_reason: 'Meeting booked',
    last_signal: 'Requested call',
    locked_until: daysAgo(-5),
    created_at: daysAgo(9),
  },
  {
    id: 'C004',
    phone: '919876543210',
    lead_id: 'L004',
    history: 'Maya: Hi Priya, Infosys has been a pioneer in digital services. How is your team managing data across client projects?\nPriya: We use different tools per project. It\'s not standardized.\nMaya: That\'s a common challenge. Our platform can provide a unified data layer across projects while maintaining client-specific isolation. Interested in seeing how?\nPriya: Yes, but I need to understand the technical architecture first. How does multi-tenancy work?\nMaya: Great question! Our multi-tenant architecture uses namespace isolation with shared infrastructure. Each client gets their own data sandbox. Want me to share the architecture doc?\nPriya: Yes, please share. I\'ll review and get back.',
    stage: 'ENGAGED',
    turn_count: 6,
    summary: 'Priya exploring multi-tenant data management for client projects. Asked technical questions.',
    last_updated: daysAgo(3),
    last_user_message: 'Yes, please share. I\'ll review and get back.',
    last_bot_message: 'Great question! Our multi-tenant architecture uses namespace isolation with shared infrastructure. Each client gets their own data sandbox. Want me to share the architecture doc?',
    last_action: 'REPLY',
    alert_sent: false,
    meeting_link_sent: false,
    brochure_sent: true,
    last_alert_reason: '',
    last_signal: 'Technical question asked',
    locked_until: '',
    created_at: daysAgo(6),
  },
  {
    id: 'C005',
    phone: '85291234567',
    lead_id: 'L008',
    history: 'Maya: Hi Jessica, StanChart\'s digital banking initiatives are impressive. How are you managing data across your regional operations?\nJessica: Please stop messaging me. I\'m not interested.\nMaya: I understand, Jessica. I\'ve noted your preference and will not contact you further. Wishing you all the best!',
    stage: 'DNC',
    turn_count: 3,
    summary: 'Lead opted out. DNC flag set.',
    last_updated: daysAgo(25),
    last_user_message: 'Please stop messaging me. I\'m not interested.',
    last_bot_message: 'I understand, Jessica. I\'ve noted your preference and will not contact you further. Wishing you all the best!',
    last_action: 'DNC',
    alert_sent: true,
    meeting_link_sent: false,
    brochure_sent: false,
    last_alert_reason: 'Lead opted out — DNC',
    last_signal: 'DNC request',
    locked_until: '',
    created_at: daysAgo(29),
  },
  {
    id: 'C006',
    phone: '919876123456',
    lead_id: 'L009',
    history: 'Maya: Hi Vikram, TCS\'s data practice is well-regarded across APAC. Are you looking for vendor-agnostic data platform tools for client delivery?\nVikram: Yes, actually. We\'re putting together an RFP for this exact use case.\nMaya: That\'s perfect timing! We\'ve worked with 3 of the top 5 IT services companies. Shall I share our partner program details?\nVikram: Please do. Also, can you support on-premise deployment? Some of our clients require it.\nMaya: Absolutely — we support cloud, on-premise, and hybrid deployments. I\'ll share the deployment options doc. When would you like to schedule a technical deep-dive?\nVikram: How about Thursday? I\'ll share the RFP draft before then.\nMaya: Thursday works perfectly! I\'ve sent you a meeting invite. Looking forward to reviewing the RFP.',
    stage: 'MEETING_BOOKED',
    turn_count: 7,
    summary: 'Vikram has an active RFP for vendor-agnostic data platform. Meeting Thursday. Will share RFP draft.',
    last_updated: daysAgo(1),
    last_user_message: 'How about Thursday? I\'ll share the RFP draft before then.',
    last_bot_message: 'Thursday works perfectly! I\'ve sent you a meeting invite. Looking forward to reviewing the RFP.',
    last_action: 'SEND_MEETING',
    alert_sent: true,
    meeting_link_sent: true,
    brochure_sent: true,
    last_alert_reason: 'RFP received — high priority',
    last_signal: 'Shared RFP document',
    locked_until: daysAgo(-2),
    created_at: daysAgo(17),
  },
  {
    id: 'C007',
    phone: '6289876543210',
    lead_id: 'L010',
    history: 'Maya: Hi Mei, Tokopedia\'s marketplace data must be fascinating. Are you working on improving product recommendation accuracy?\nMei: Yes, data quality is a big issue for our rec engine. What do you offer?\nMaya: We specialize in data quality tools that can clean and enrich product data at scale. Want me to share how we\'ve helped similar e-commerce platforms?',
    stage: 'CURIOUS',
    turn_count: 3,
    summary: 'Mei interested in data quality for recommendation engine. Early stage.',
    last_updated: daysAgo(3),
    last_user_message: 'Yes, data quality is a big issue for our rec engine. What do you offer?',
    last_bot_message: 'We specialize in data quality tools that can clean and enrich product data at scale. Want me to share how we\'ve helped similar e-commerce platforms?',
    last_action: 'REPLY',
    alert_sent: false,
    meeting_link_sent: false,
    brochure_sent: false,
    last_alert_reason: '',
    last_signal: 'Product interest',
    locked_until: '',
    created_at: daysAgo(3),
  },
  {
    id: 'C008',
    phone: '971552345678',
    lead_id: 'L012',
    history: 'Maya: Hi Fatima, Emirates NBD\'s data strategy has been groundbreaking. As CDO, what\'s your biggest data challenge right now?\nFatima: We need an enterprise-wide data governance framework. Our current tools are fragmented.\nMaya: Enterprise governance is our strength. We\'ve implemented governance frameworks at 8 major banks. Would you like to see our approach?\nFatima: Yes, but I want to understand the full picture. Can we set up a meeting with your leadership?\nMaya: Absolutely! I can arrange a meeting with our CEO and Solutions team. When works for you?\nFatima: Next week, preferably Tuesday or Wednesday. We\'re targeting Q3 implementation.',
    stage: 'QUALIFIED',
    turn_count: 6,
    summary: 'CDO at Emirates NBD wants enterprise governance framework. Requesting CEO-level meeting. Q3 target.',
    last_updated: hoursAgo(10),
    last_user_message: 'Next week, preferably Tuesday or Wednesday. We\'re targeting Q3 implementation.',
    last_bot_message: 'Absolutely! I can arrange a meeting with our CEO and Solutions team. When works for you?',
    last_action: 'REPLY',
    alert_sent: true,
    meeting_link_sent: false,
    brochure_sent: false,
    last_alert_reason: 'CDO requesting CEO meeting',
    last_signal: 'Requested leadership meeting',
    locked_until: '',
    created_at: daysAgo(14),
  },
];

// ---------------------------------------------------------------------------
// PARSED MESSAGES (for WhatsApp view)
// ---------------------------------------------------------------------------
export function parseConversationMessages(conversation: Conversation): Message[] {
  if (!conversation.history) return [];
  const lines = conversation.history.split('\n').filter(l => l.trim());
  return lines.map((line, i) => {
    const isBot = line.startsWith('Maya:');
    const content = line.replace(/^(Maya|[A-Za-z]+):\s*/, '');
    return {
      id: `${conversation.id}-M${i}`,
      sender: isBot ? 'bot' : 'lead',
      content,
      timestamp: new Date(new Date(conversation.created_at).getTime() + i * 3600000 * 4).toISOString(),
    };
  });
}

// ---------------------------------------------------------------------------
// APPOINTMENTS
// ---------------------------------------------------------------------------
export const mockAppointments: Appointment[] = [
  {
    id: 'A001',
    lead_id: 'L002',
    lead_name: 'Sarah Tan',
    phone: '6591234567',
    date: new Date(now.getTime() + 2 * 86400000).toISOString().split('T')[0],
    time: '14:00',
    status: 'ai_booked',
    meeting_link: 'https://meet.google.com/abc-defg-hij',
    conversation_summary: 'Sarah needs a CDP. Will bring Head of Engineering.',
    created_at: daysAgo(2),
  },
  {
    id: 'A002',
    lead_id: 'L003',
    lead_name: 'Omar Al Hammadi',
    phone: '971501234567',
    date: new Date(now.getTime() + 4 * 86400000).toISOString().split('T')[0],
    time: '10:00',
    status: 'ai_booked',
    meeting_link: 'https://meet.google.com/klm-nopq-rst',
    conversation_summary: 'Omar needs CBUAE compliance support.',
    created_at: hoursAgo(18),
  },
  {
    id: 'A003',
    lead_id: 'L009',
    lead_name: 'Vikram Desai',
    phone: '919876123456',
    date: new Date(now.getTime() + 1 * 86400000).toISOString().split('T')[0],
    time: '11:00',
    status: 'qc_confirmed',
    meeting_link: 'https://meet.google.com/uvw-xyz1-234',
    conversation_summary: 'Vikram has RFP for vendor-agnostic data platform. Will share RFP draft.',
    created_at: daysAgo(1),
  },
  {
    id: 'A004',
    lead_id: 'L012',
    lead_name: 'Fatima Al Zahra',
    phone: '971552345678',
    date: new Date(now.getTime() + 5 * 86400000).toISOString().split('T')[0],
    time: '15:00',
    status: 'meeting_scheduled',
    meeting_link: 'https://meet.google.com/567-890a-bcd',
    conversation_summary: 'CDO requesting CEO-level meeting. Q3 governance implementation target.',
    created_at: hoursAgo(10),
  },
  {
    id: 'A005',
    lead_id: 'L001',
    lead_name: 'Rajesh Kumar',
    phone: '6281234567890',
    date: new Date(now.getTime() + 1 * 86400000).toISOString().split('T')[0],
    time: '15:30',
    status: 'ai_booked',
    meeting_link: 'https://meet.google.com/efg-hijk-lmn',
    conversation_summary: 'Compliance-focused demo. Solutions architect team joining.',
    created_at: hoursAgo(6),
  },
  {
    id: 'A006',
    lead_id: 'L020',
    lead_name: 'Mohammed Al Rashid',
    phone: '966551234567',
    date: new Date(now.getTime() + 3 * 86400000).toISOString().split('T')[0],
    time: '09:00',
    status: 'meeting_scheduled',
    meeting_link: 'https://meet.google.com/opq-rstu-vwx',
    conversation_summary: 'On-premise deployment discussion for Saudi Aramco.',
    created_at: daysAgo(1),
  },
  {
    id: 'A007',
    lead_id: 'L024',
    lead_name: 'Rashid Khan',
    phone: '97339876543',
    date: new Date(now.getTime() - 2 * 86400000).toISOString().split('T')[0],
    time: '13:00',
    status: 'qc_confirmed',
    meeting_link: 'https://meet.google.com/yza-bcde-fgh',
    conversation_summary: 'Core banking migration assessment.',
    created_at: daysAgo(5),
  },
];

// ---------------------------------------------------------------------------
// KNOWLEDGE BASE DOCUMENTS
// ---------------------------------------------------------------------------
export const mockKnowledgeDocs: KnowledgeDoc[] = [
  { id: 'K001', title: 'Artha Platform Overview', filename: 'artha-platform-overview.pdf', category: 'Product Doc', industry_tag: 'General', date_added: daysAgo(60), uploaded_by: 'Anirudh Yadav', file_size: 2457600, status: 'ready' },
  { id: 'K002', title: 'Master Data Management Guide', filename: 'mdm-guide-v2.pdf', category: 'Product Doc', industry_tag: 'General', date_added: daysAgo(45), uploaded_by: 'Anirudh Yadav', file_size: 1843200, status: 'ready' },
  { id: 'K003', title: 'Banking Case Study — DBS', filename: 'case-study-dbs.pdf', category: 'Case Study', industry_tag: 'Banking', date_added: daysAgo(30), uploaded_by: 'Sales Team', file_size: 921600, status: 'ready' },
  { id: 'K004', title: 'Data Insights Platform (DIP) Spec', filename: 'dip-product-spec.pdf', category: 'Product Doc', industry_tag: 'General', date_added: daysAgo(25), uploaded_by: 'Anirudh Yadav', file_size: 3276800, status: 'ready' },
  { id: 'K005', title: 'Competitor Analysis — Informatica vs Artha', filename: 'competitor-informatica.pdf', category: 'Competitor Intel', industry_tag: 'General', date_added: daysAgo(20), uploaded_by: 'Sales Team', file_size: 614400, status: 'ready' },
  { id: 'K006', title: 'BETL Product Sheet', filename: 'betl-product-sheet.pdf', category: 'Product Doc', industry_tag: 'General', date_added: daysAgo(15), uploaded_by: 'Anirudh Yadav', file_size: 1228800, status: 'ready' },
  { id: 'K007', title: 'Oil & Gas Case Study — ADNOC', filename: 'case-study-adnoc.pdf', category: 'Case Study', industry_tag: 'Oil & Gas', date_added: daysAgo(10), uploaded_by: 'Sales Team', file_size: 1024000, status: 'ready' },
  { id: 'K008', title: 'Sales Objection Handling Playbook', filename: 'objection-handling.pdf', category: 'Sales Tactic', industry_tag: 'General', date_added: daysAgo(5), uploaded_by: 'Sales Team', file_size: 512000, status: 'ready' },
];

// ---------------------------------------------------------------------------
// UNANSWERED QUESTIONS (Knowledge Gap Detector)
// ---------------------------------------------------------------------------
export const mockUnansweredQuestions: UnansweredQuestion[] = [
  { id: 'UQ001', question: 'What are your pricing tiers for enterprise customers?', lead_name: 'Sarah Tan', lead_id: 'L002', asked_at: daysAgo(3), similarity_score: 0.23, times_asked: 5 },
  { id: 'UQ002', question: 'Do you support on-premise deployment in air-gapped environments?', lead_name: 'Mohammed Al Rashid', lead_id: 'L020', asked_at: daysAgo(2), similarity_score: 0.31, times_asked: 3 },
  { id: 'UQ003', question: 'What SLA do you offer for 99.99% uptime?', lead_name: 'Wei Chen', lead_id: 'L007', asked_at: daysAgo(1), similarity_score: 0.18, times_asked: 4 },
  { id: 'UQ004', question: 'How does your platform handle GDPR and PDPA compliance simultaneously?', lead_name: 'Tan Boon Keat', lead_id: 'L021', asked_at: hoursAgo(12), similarity_score: 0.29, times_asked: 2 },
  { id: 'UQ005', question: 'Can you integrate with SAP S/4HANA?', lead_name: 'Deepak Mehta', lead_id: 'L015', asked_at: hoursAgo(6), similarity_score: 0.15, times_asked: 3 },
];

// ---------------------------------------------------------------------------
// USERS
// ---------------------------------------------------------------------------
export const mockUsers: User[] = [
  { id: 'U001', name: 'Anirudh Yadav', email: 'anirudhpsyadav@gmail.com', role: 'admin', status: 'active', last_login: hoursAgo(1), created_at: daysAgo(90), avatar_url: '' },
  { id: 'U002', name: 'Rahul Gupta', email: 'rahul@artha.ai', role: 'ceo', status: 'active', last_login: hoursAgo(3), created_at: daysAgo(90), avatar_url: '' },
  { id: 'U003', name: 'Prashant Singh', email: 'prashant@artha.ai', role: 'sales_head', status: 'active', last_login: hoursAgo(2), created_at: daysAgo(60), avatar_url: '' },
  { id: 'U004', name: 'Syed Ahmed', email: 'syed@artha.ai', role: 'country_head', status: 'active', country: 'UAE', last_login: daysAgo(1), created_at: daysAgo(45), avatar_url: '' },
  { id: 'U005', name: 'Maria Santos', email: 'maria@artha.ai', role: 'country_head', status: 'active', country: 'Singapore', last_login: hoursAgo(5), created_at: daysAgo(45), avatar_url: '' },
  { id: 'U006', name: 'Rohit Kapoor', email: 'rohit@artha.ai', role: 'sales_rep', status: 'active', last_login: hoursAgo(1), created_at: daysAgo(30), avatar_url: '' },
  { id: 'U007', name: 'Sneha Reddy', email: 'sneha@artha.ai', role: 'sales_rep', status: 'active', last_login: hoursAgo(4), created_at: daysAgo(30), avatar_url: '' },
  { id: 'U008', name: 'Kartik Menon', email: 'kartik@artha.ai', role: 'sales_rep', status: 'invited', last_login: '', created_at: daysAgo(2), avatar_url: '' },
];

// ---------------------------------------------------------------------------
// ACTIVITY FEED
// ---------------------------------------------------------------------------
export const mockActivityFeed: ActivityEvent[] = [
  { id: 'E001', type: 'new_lead', message: 'New lead added: Putri Wijaya (Gojek)', lead_name: 'Putri Wijaya', lead_id: 'L023', timestamp: hoursAgo(20), icon: '🟢' },
  { id: 'E002', type: 'reply', message: 'Maya replied to Rajesh Kumar', lead_name: 'Rajesh Kumar', lead_id: 'L001', timestamp: hoursAgo(6), icon: '💬' },
  { id: 'E003', type: 'meeting_booked', message: 'Meeting booked with Omar Al Hammadi', lead_name: 'Omar Al Hammadi', lead_id: 'L003', timestamp: hoursAgo(18), icon: '📅' },
  { id: 'E004', type: 'stage_change', message: 'Rajesh Kumar moved to QUALIFIED', lead_name: 'Rajesh Kumar', lead_id: 'L001', timestamp: hoursAgo(8), icon: '⬆️' },
  { id: 'E005', type: 'reply', message: 'Maya replied to Arjun Reddy', lead_name: 'Arjun Reddy', lead_id: 'L027', timestamp: hoursAgo(3), icon: '💬' },
  { id: 'E006', type: 'alert', message: 'Handoff alert: Fatima Al Zahra requested CEO meeting', lead_name: 'Fatima Al Zahra', lead_id: 'L012', timestamp: hoursAgo(10), icon: '🔔' },
  { id: 'E007', type: 'reply', message: 'Maya replied to Li Wei', lead_name: 'Li Wei', lead_id: 'L018', timestamp: hoursAgo(4), icon: '💬' },
  { id: 'E008', type: 'stage_change', message: 'Vikram Desai moved to MEETING_BOOKED', lead_name: 'Vikram Desai', lead_id: 'L009', timestamp: daysAgo(1), icon: '⬆️' },
  { id: 'E009', type: 'knowledge_upload', message: 'New document uploaded: Sales Objection Handling Playbook', timestamp: daysAgo(5), icon: '📁' },
  { id: 'E010', type: 'dnc', message: 'DNC: lead opted out — Jessica Morgan', lead_name: 'Jessica Morgan', lead_id: 'L008', timestamp: daysAgo(25), icon: '🔴' },
  { id: 'E011', type: 'reply', message: 'Maya replied to Fatima Al Zahra', lead_name: 'Fatima Al Zahra', lead_id: 'L012', timestamp: hoursAgo(10), icon: '💬' },
  { id: 'E012', type: 'new_lead', message: 'New lead added: Thuy Nguyen (VPBank)', lead_name: 'Thuy Nguyen', lead_id: 'L028', timestamp: daysAgo(2), icon: '🟢' },
  { id: 'E013', type: 'meeting_booked', message: 'Meeting booked with Sarah Tan', lead_name: 'Sarah Tan', lead_id: 'L002', timestamp: daysAgo(2), icon: '📅' },
  { id: 'E014', type: 'reply', message: 'Maya replied to Deepak Mehta', lead_name: 'Deepak Mehta', lead_id: 'L015', timestamp: daysAgo(1), icon: '💬' },
  { id: 'E015', type: 'alert', message: 'Alert: Vikram Desai shared RFP document', lead_name: 'Vikram Desai', lead_id: 'L009', timestamp: daysAgo(1), icon: '🔔' },
];

// ---------------------------------------------------------------------------
// DASHBOARD KPIs
// ---------------------------------------------------------------------------
export const mockDashboardKPIs: DashboardKPIs = {
  total_leads: 30,
  new_leads: 5,
  sales_ready: 5,
  qualified: 6,
  meetings_booked: 4,
  active_conversations: 22,
};

// ---------------------------------------------------------------------------
// TREND DATA
// ---------------------------------------------------------------------------
export const mockTrendData: TrendDataPoint[] = [
  { date: daysAgo(28).split('T')[0], value: 12 },
  { date: daysAgo(24).split('T')[0], value: 15 },
  { date: daysAgo(21).split('T')[0], value: 18 },
  { date: daysAgo(17).split('T')[0], value: 14 },
  { date: daysAgo(14).split('T')[0], value: 22 },
  { date: daysAgo(10).split('T')[0], value: 28 },
  { date: daysAgo(7).split('T')[0], value: 25 },
  { date: daysAgo(3).split('T')[0], value: 32 },
  { date: daysAgo(0).split('T')[0], value: 30 },
];

// ---------------------------------------------------------------------------
// LEAD DISTRIBUTION
// ---------------------------------------------------------------------------
export const mockLeadDistribution: LeadDistribution[] = [
  { tier: 'Sales Ready', count: 5, color: '#22C55E' },
  { tier: 'Qualified', count: 6, color: '#F97316' },
  { tier: 'Engaged', count: 8, color: '#F59E0B' },
  { tier: 'Exploring', count: 5, color: '#3B82F6' },
  { tier: 'Dormant', count: 6, color: '#9CA3AF' },
];

// ---------------------------------------------------------------------------
// SYSTEM STATUS
// ---------------------------------------------------------------------------
export const mockSystemStatus: SystemStatus = {
  status: 'healthy',
  last_checked: minutesAgo(2),
  message: 'All systems running',
};

// ---------------------------------------------------------------------------
// ROLE PERMISSIONS
// ---------------------------------------------------------------------------
export const mockRolePermissions: RolePermissions[] = [
  {
    role: 'admin',
    label: 'Developer / Admin',
    permissions: [
      { module: 'leads', actions: ['view', 'create', 'edit', 'delete', 'export'] },
      { module: 'whatsapp', actions: ['view', 'take_over'] },
      { module: 'appointments', actions: ['view', 'manage'] },
      { module: 'knowledge_base', actions: ['view', 'upload', 'delete'] },
      { module: 'users', actions: ['view', 'create', 'edit', 'delete', 'manage'] },
      { module: 'roles', actions: ['view', 'manage'] },
      { module: 'settings', actions: ['view', 'manage'] },
    ],
  },
  {
    role: 'ceo',
    label: 'CEO',
    permissions: [
      { module: 'leads', actions: ['view', 'create', 'edit', 'delete', 'export'] },
      { module: 'whatsapp', actions: ['view', 'take_over'] },
      { module: 'appointments', actions: ['view', 'manage'] },
      { module: 'knowledge_base', actions: ['view', 'upload', 'delete'] },
      { module: 'users', actions: ['view'] },
      { module: 'roles', actions: ['view'] },
      { module: 'settings', actions: ['view'] },
    ],
  },
  {
    role: 'country_head',
    label: 'Country Head',
    permissions: [
      { module: 'leads', actions: ['view', 'create', 'edit', 'export'] },
      { module: 'whatsapp', actions: ['view', 'take_over'] },
      { module: 'appointments', actions: ['view', 'manage'] },
      { module: 'knowledge_base', actions: ['view', 'upload', 'delete'] },
      { module: 'users', actions: ['view'] },
      { module: 'roles', actions: ['view'] },
      { module: 'settings', actions: [] },
    ],
  },
  {
    role: 'sales_head',
    label: 'Sales Head',
    permissions: [
      { module: 'leads', actions: ['view', 'create', 'edit', 'export'] },
      { module: 'whatsapp', actions: ['view', 'take_over'] },
      { module: 'appointments', actions: ['view', 'manage'] },
      { module: 'knowledge_base', actions: ['view', 'upload', 'delete'] },
      { module: 'users', actions: ['view'] },
      { module: 'roles', actions: [] },
      { module: 'settings', actions: [] },
    ],
  },
  {
    role: 'sales_rep',
    label: 'Sales Rep / Staff',
    permissions: [
      { module: 'leads', actions: ['view'] },
      { module: 'whatsapp', actions: ['view', 'take_over'] },
      { module: 'appointments', actions: ['view'] },
      { module: 'knowledge_base', actions: ['view'] },
      { module: 'users', actions: [] },
      { module: 'roles', actions: [] },
      { module: 'settings', actions: [] },
    ],
  },
];
